// Bug happens on JVM 
// FILE: tmp0.kt


fun box()  = 
"".plus(try {}
catch(e: NoWhenBranchMatchedException){
{a
 -> 
 }
}
)



// org.jetbrains.kotlin.backend.common.BackendException: Backend Internal error: Exception during IR lowering
// File being compiled: /home/stepanov/Kotlin/bbfgradle/tmp/tmp0.kt
// The root cause java.lang.IllegalStateException was thrown at: org.jetbrains.kotlin.backend.jvm.ir.IrUtilsKt.getErasedUpperBound(IrUtils.kt:117)
// 	at org.jetbrains.kotlin.backend.common.CodegenUtil.reportBackendException(CodegenUtil.kt:239)
// 	at org.jetbrains.kotlin.backend.common.CodegenUtil.reportBackendException$default(CodegenUtil.kt:235)
// 	at org.jetbrains.kotlin.backend.common.phaser.PerformByIrFilePhase.invokeSequential(performByIrFile.kt:68)
// 	at org.jetbrains.kotlin.backend.common.phaser.PerformByIrFilePhase.invoke(performByIrFile.kt:55)
// 	at org.jetbrains.kotlin.backend.common.phaser.PerformByIrFilePhase.invoke(performByIrFile.kt:41)
// 	at org.jetbrains.kotlin.backend.common.phaser.NamedCompilerPhase.invoke(CompilerPhase.kt:96)
// 	at org.jetbrains.kotlin.backend.common.phaser.CompositePhase.invoke(PhaseBuilders.kt:29)
// 	at org.jetbrains.kotlin.backend.common.phaser.NamedCompilerPhase.invoke(CompilerPhase.kt:96)
// 	at org.jetbrains.kotlin.backend.common.phaser.CompositePhase.invoke(PhaseBuilders.kt:22)
// 	at org.jetbrains.kotlin.backend.common.phaser.NamedCompilerPhase.invoke(CompilerPhase.kt:96)
// 	at org.jetbrains.kotlin.backend.common.phaser.CompilerPhaseKt.invokeToplevel(CompilerPhase.kt:43)
// 	at org.jetbrains.kotlin.backend.jvm.JvmIrCodegenFactory.doGenerateFilesInternal(JvmIrCodegenFactory.kt:191)
// 	at org.jetbrains.kotlin.backend.jvm.JvmIrCodegenFactory.generateModule(JvmIrCodegenFactory.kt:60)
// 	at org.jetbrains.kotlin.codegen.KotlinCodegenFacade.compileCorrectFiles(KotlinCodegenFacade.java:35)
// 	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.generate(KotlinToJVMBytecodeCompiler.kt:321)
// 	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:113)
// 	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli$default(KotlinToJVMBytecodeCompiler.kt:56)
// 	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:169)
// 	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:52)
// 	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:92)
// 	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:44)
// 	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:98)
// 	at com.stepanov.bbf.bugfinder.executor.compilers.JVMCompiler.executeCompiler$lambda-3(JVMCompiler.kt:115)
// 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
// 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
// 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
// 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
// 	at java.base/java.lang.Thread.run(Thread.java:832)
// Caused by: java.lang.IllegalStateException: IrErrorType([ERROR : <Unknown lambda parameter type>])
// 	at org.jetbrains.kotlin.backend.jvm.ir.IrUtilsKt.getErasedUpperBound(IrUtils.kt:117)
// 	at org.jetbrains.kotlin.backend.jvm.lower.inlineclasses.InlineClassAbiKt.getRequiresMangling(InlineClassAbi.kt:123)
// 	at org.jetbrains.kotlin.backend.jvm.lower.inlineclasses.InlineClassAbiKt.getHasMangledParameters(InlineClassAbi.kt:132)
// 	at org.jetbrains.kotlin.backend.jvm.lower.inlineclasses.MemoizedInlineClassReplacements$getReplacementFunction$1.invoke(MemoizedInlineClassReplacements.kt:84)
// 	at org.jetbrains.kotlin.backend.jvm.lower.inlineclasses.MemoizedInlineClassReplacements$getReplacementFunction$1.invoke(MemoizedInlineClassReplacements.kt:54)
// 	at org.jetbrains.kotlin.storage.LockBasedStorageManager$MapBasedMemoizedFunction.invoke(LockBasedStorageManager.java:578)
// 	at org.jetbrains.kotlin.backend.jvm.lower.JvmInlineClassLowering.transformFunctionFlat(JvmInlineClassLowering.kt:118)
// 	at org.jetbrains.kotlin.backend.jvm.lower.JvmInlineClassLowering.access$transformFunctionFlat(JvmInlineClassLowering.kt:63)
// 	at org.jetbrains.kotlin.backend.jvm.lower.JvmInlineClassLowering$visitClassNew$2.invoke(JvmInlineClassLowering.kt:82)
// 	at org.jetbrains.kotlin.backend.jvm.lower.JvmInlineClassLowering$visitClassNew$2.invoke(JvmInlineClassLowering.kt:80)
// 	at org.jetbrains.kotlin.ir.util.TransformKt.transformDeclarationsFlat(transform.kt:94)
// 	at org.jetbrains.kotlin.backend.jvm.lower.JvmInlineClassLowering.visitClassNew(JvmInlineClassLowering.kt:80)
// 	at org.jetbrains.kotlin.backend.common.IrElementTransformerVoidWithContext.visitClass(IrElementTransformerVoidWithContext.kt:47)
// 	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitClass(IrElementTransformerVoid.kt:67)
// 	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitClass(IrElementTransformerVoid.kt:24)
// 	at org.jetbrains.kotlin.ir.declarations.IrClass.accept(IrClass.kt:55)
// 	at org.jetbrains.kotlin.ir.IrElement$DefaultImpls.transform(IrElement.kt:32)
// 	at org.jetbrains.kotlin.ir.IrElementBase.transform(IrElementBase.kt:19)
// 	at org.jetbrains.kotlin.ir.IrElementKt.transformStatement(IrElement.kt:40)
// 	at org.jetbrains.kotlin.backend.jvm.lower.JvmInlineClassLowering.visitStatementContainer(JvmInlineClassLowering.kt:450)
// 	at org.jetbrains.kotlin.backend.jvm.lower.JvmInlineClassLowering.visitContainerExpression(JvmInlineClassLowering.kt:455)
// 	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitBlock(IrElementTransformerVoid.kt:153)
// 	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitBlock(IrElementTransformerVoid.kt:154)
// 	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitBlock(IrElementTransformerVoid.kt:24)
// 	at org.jetbrains.kotlin.ir.expressions.impl.IrBlockImpl.accept(IrBlockImpl.kt:48)
// 	at org.jetbrains.kotlin.ir.expressions.IrExpression.transform(IrExpression.kt:33)
// 	at org.jetbrains.kotlin.ir.expressions.IrExpression.transform(IrExpression.kt:26)
// 	at org.jetbrains.kotlin.ir.IrElementKt.transformStatement(IrElement.kt:40)
// 	at org.jetbrains.kotlin.backend.jvm.lower.JvmInlineClassLowering.visitStatementContainer(JvmInlineClassLowering.kt:450)
// 	at org.jetbrains.kotlin.backend.jvm.lower.JvmInlineClassLowering.visitContainerExpression(JvmInlineClassLowering.kt:455)
// 	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitBlock(IrElementTransformerVoid.kt:153)
// 	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitBlock(IrElementTransformerVoid.kt:154)
// 	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitBlock(IrElementTransformerVoid.kt:24)
// 	at org.jetbrains.kotlin.ir.expressions.impl.IrBlockImpl.accept(IrBlockImpl.kt:48)
// 	at org.jetbrains.kotlin.ir.expressions.IrExpression.transform(IrExpression.kt:33)
// 	at org.jetbrains.kotlin.ir.expressions.impl.IrCatchImpl.transformChildren(IrTryImpl.kt:98)
// 	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitCatch(IrElementTransformerVoid.kt:277)
// 	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitCatch(IrElementTransformerVoid.kt:281)
// 	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitCatch(IrElementTransformerVoid.kt:24)
// 	at org.jetbrains.kotlin.ir.expressions.impl.IrCatchImpl.accept(IrTryImpl.kt:88)
// 	at org.jetbrains.kotlin.ir.IrElement$DefaultImpls.transform(IrElement.kt:32)
// 	at org.jetbrains.kotlin.ir.IrElementBase.transform(IrElementBase.kt:19)
// 	at org.jetbrains.kotlin.ir.expressions.IrCatch.transform(IrTry.kt:36)
// 	at org.jetbrains.kotlin.ir.expressions.impl.IrTryImpl.transformChildren(IrTryImpl.kt:65)
// 	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitExpression(IrElementTransformerVoid.kt:131)
// 	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitTry(IrElementTransformerVoid.kt:273)
// 	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitTry(IrElementTransformerVoid.kt:274)
// 	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitTry(IrElementTransformerVoid.kt:24)
// 	at org.jetbrains.kotlin.ir.expressions.impl.IrTryImpl.accept(IrTryImpl.kt:53)
// 	at org.jetbrains.kotlin.ir.expressions.IrExpression.transform(IrExpression.kt:33)
// 	at org.jetbrains.kotlin.ir.expressions.IrFunctionAccessExpression.transformChildren(IrFunctionAccessExpression.kt:48)
// 	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitExpression(IrElementTransformerVoid.kt:131)
// 	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitMemberAccess(IrElementTransformerVoid.kt:192)
// 	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitFunctionAccess(IrElementTransformerVoid.kt:195)
// 	at org.jetbrains.kotlin.backend.jvm.lower.JvmInlineClassLowering.visitFunctionAccess(JvmInlineClassLowering.kt:308)
// 	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitCall(IrElementTransformerVoid.kt:198)
// 	at org.jetbrains.kotlin.backend.jvm.lower.JvmInlineClassLowering.visitCall(JvmInlineClassLowering.kt:406)
// 	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitCall(IrElementTransformerVoid.kt:199)
// 	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitCall(IrElementTransformerVoid.kt:24)
// 	at org.jetbrains.kotlin.ir.expressions.impl.IrCallImpl.accept(IrCallImpl.kt:47)
// 	at org.jetbrains.kotlin.ir.expressions.IrExpression.transform(IrExpression.kt:33)
// 	at org.jetbrains.kotlin.ir.expressions.impl.IrReturnImpl.transformChildren(IrReturnImpl.kt:41)
// 	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitExpression(IrElementTransformerVoid.kt:131)
// 	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitReturn(IrElementTransformerVoid.kt:292)
// 	at org.jetbrains.kotlin.backend.jvm.lower.JvmInlineClassLowering.visitReturn(JvmInlineClassLowering.kt:442)
// 	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitReturn(IrElementTransformerVoid.kt:293)
// 	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitReturn(IrElementTransformerVoid.kt:24)
// 	at org.jetbrains.kotlin.ir.expressions.impl.IrReturnImpl.accept(IrReturnImpl.kt:34)
// 	at org.jetbrains.kotlin.ir.expressions.IrExpression.transform(IrExpression.kt:33)
// 	at org.jetbrains.kotlin.ir.expressions.IrExpression.transform(IrExpression.kt:26)
// 	at org.jetbrains.kotlin.ir.IrElementKt.transformStatement(IrElement.kt:40)
// 	at org.jetbrains.kotlin.backend.jvm.lower.JvmInlineClassLowering.visitStatementContainer(JvmInlineClassLowering.kt:450)
// 	at org.jetbrains.kotlin.backend.jvm.lower.JvmInlineClassLowering.visitBlockBody(JvmInlineClassLowering.kt:460)
// 	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitBlockBody(IrElementTransformerVoid.kt:118)
// 	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitBlockBody(IrElementTransformerVoid.kt:24)
// 	at org.jetbrains.kotlin.ir.expressions.IrBlockBody.accept(IrBody.kt:54)
// 	at org.jetbrains.kotlin.ir.expressions.IrBody.transform(IrBody.kt:27)
// 	at org.jetbrains.kotlin.ir.declarations.IrFunction.transformChildren(IrFunction.kt:68)
// 	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoidKt.transformChildrenVoid(IrElementTransformerVoid.kt:330)
// 	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.transformChildrenVoid(IrElementTransformerVoid.kt:325)
// 	at org.jetbrains.kotlin.backend.jvm.lower.JvmInlineClassLowering.transformFunctionFlat(JvmInlineClassLowering.kt:120)
// 	at org.jetbrains.kotlin.backend.jvm.lower.JvmInlineClassLowering.access$transformFunctionFlat(JvmInlineClassLowering.kt:63)
// 	at org.jetbrains.kotlin.backend.jvm.lower.JvmInlineClassLowering$visitClassNew$2.invoke(JvmInlineClassLowering.kt:82)
// 	at org.jetbrains.kotlin.backend.jvm.lower.JvmInlineClassLowering$visitClassNew$2.invoke(JvmInlineClassLowering.kt:80)
// 	at org.jetbrains.kotlin.ir.util.TransformKt.transformDeclarationsFlat(transform.kt:94)
// 	at org.jetbrains.kotlin.backend.jvm.lower.JvmInlineClassLowering.visitClassNew(JvmInlineClassLowering.kt:80)
// 	at org.jetbrains.kotlin.backend.common.IrElementTransformerVoidWithContext.visitClass(IrElementTransformerVoidWithContext.kt:47)
// 	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitClass(IrElementTransformerVoid.kt:67)
// 	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitClass(IrElementTransformerVoid.kt:24)
// 	at org.jetbrains.kotlin.ir.declarations.IrClass.accept(IrClass.kt:55)
// 	at org.jetbrains.kotlin.ir.IrElement$DefaultImpls.transform(IrElement.kt:32)
// 	at org.jetbrains.kotlin.ir.IrElementBase.transform(IrElementBase.kt:19)
// 	at org.jetbrains.kotlin.ir.declarations.impl.IrFileImpl.transformChildren(IrFileImpl.kt:89)
// 	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoidKt.transformChildrenVoid(IrElementTransformerVoid.kt:330)
// 	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.transformChildrenVoid(IrElementTransformerVoid.kt:325)
// 	at org.jetbrains.kotlin.backend.jvm.lower.JvmInlineClassLowering.lower(JvmInlineClassLowering.kt:72)
// 	at org.jetbrains.kotlin.backend.common.phaser.FileLoweringPhaseAdapter.invoke(PhaseBuilders.kt:120)
// 	at org.jetbrains.kotlin.backend.common.phaser.FileLoweringPhaseAdapter.invoke(PhaseBuilders.kt:116)
// 	at org.jetbrains.kotlin.backend.common.phaser.NamedCompilerPhase.invoke(CompilerPhase.kt:96)
// 	at org.jetbrains.kotlin.backend.common.phaser.PerformByIrFilePhase.invokeSequential(performByIrFile.kt:65)
// 	... 25 more
// 