// Bug happens on JS -Xir-produce-js ver 1.6.0-dev-1486
// FILE: tmp0.kt


fun foo()  =
foldingBuiltinBinary(null )
inline fun foldingBuiltinBinary(int1: Int?
) {
    int1!!
for (e in int1..
1)
for (m in "") {}
}

// STACKTRACE:
// java.util.NoSuchElementException: Sequence contains no element matching the predicate.
// 	at org.jetbrains.kotlin.backend.common.lower.loops.UtilsKt.castIfNecessary(Utils.kt:153)
// 	at org.jetbrains.kotlin.backend.common.lower.loops.ProgressionType.asElementType(ProgressionType.kt:36)
// 	at org.jetbrains.kotlin.backend.common.lower.loops.NumericForLoopHeader.<init>(HeaderProcessor.kt:94)
// 	at org.jetbrains.kotlin.backend.common.lower.loops.ProgressionLoopHeader.<init>(HeaderProcessor.kt:253)
// 	at org.jetbrains.kotlin.backend.common.lower.loops.HeaderProcessor.extractHeader(HeaderProcessor.kt:664)
// 	at org.jetbrains.kotlin.backend.common.lower.loops.RangeLoopTransformer.visitBlock(ForLoopsLowering.kt:167)
// 	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitBlock(IrElementTransformerVoid.kt:154)
// 	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitBlock(IrElementTransformerVoid.kt:24)
// 	at org.jetbrains.kotlin.ir.expressions.impl.IrBlockImpl.accept(IrBlockImpl.kt:48)
// 	at org.jetbrains.kotlin.ir.expressions.IrExpression.transform(IrExpression.kt:33)
// 	at org.jetbrains.kotlin.ir.expressions.IrExpression.transform(IrExpression.kt:26)
// 	at org.jetbrains.kotlin.ir.expressions.impl.IrReturnableBlockImpl.transformChildren(IrBlockImpl.kt:100)
// 	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitExpression(IrElementTransformerVoid.kt:131)
// 	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitContainerExpression(IrElementTransformerVoid.kt:150)
// 	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitBlock(IrElementTransformerVoid.kt:153)
// 	at org.jetbrains.kotlin.backend.common.lower.loops.RangeLoopTransformer.visitBlock(ForLoopsLowering.kt:160)
// 	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitBlock(IrElementTransformerVoid.kt:154)
// 	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitBlock(IrElementTransformerVoid.kt:24)
// 	at org.jetbrains.kotlin.ir.expressions.impl.IrReturnableBlockImpl.accept(IrBlockImpl.kt:92)
// 	at org.jetbrains.kotlin.ir.expressions.IrExpression.transform(IrExpression.kt:33)
// 	at org.jetbrains.kotlin.ir.expressions.IrExpression.transform(IrExpression.kt:26)
// 	at org.jetbrains.kotlin.ir.expressions.IrBlockBody.transformChildren(IrBody.kt:62)
// 	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoidKt.transformChildrenVoid(IrElementTransformerVoid.kt:330)
// 	at org.jetbrains.kotlin.backend.common.lower.loops.ForLoopsLowering.lower(ForLoopsLowering.kt:105)
// 	at org.jetbrains.kotlin.backend.common.BodyLoweringVisitor$visitBody$1.invoke(Lower.kt:157)
// 	at org.jetbrains.kotlin.backend.common.BodyLoweringVisitor$visitBody$1.invoke(Lower.kt:156)
// 	at org.jetbrains.kotlin.ir.declarations.StageController.bodyLowering(PersistentApi.kt:25)
// 	at org.jetbrains.kotlin.backend.common.BodyLoweringVisitor.visitBody(Lower.kt:156)
// 	at org.jetbrains.kotlin.backend.common.BodyLoweringVisitor.visitBody(Lower.kt:132)
// 	at org.jetbrains.kotlin.ir.visitors.IrElementVisitor$DefaultImpls.visitBlockBody(IrElementVisitor.kt:48)
// 	at org.jetbrains.kotlin.backend.common.BodyLoweringVisitor.visitBlockBody(Lower.kt:132)
// 	at org.jetbrains.kotlin.backend.common.BodyLoweringVisitor.visitBlockBody(Lower.kt:132)
// 	at org.jetbrains.kotlin.ir.expressions.IrBlockBody.accept(IrBody.kt:54)
// 	at org.jetbrains.kotlin.ir.declarations.IrFunction.acceptChildren(IrFunction.kt:58)
// 	at org.jetbrains.kotlin.backend.common.BodyLoweringVisitor.visitDeclaration(Lower.kt:142)
// 	at org.jetbrains.kotlin.backend.common.BodyLoweringVisitor.visitDeclaration(Lower.kt:132)
// 	at org.jetbrains.kotlin.ir.visitors.IrElementVisitor$DefaultImpls.visitFunction(IrElementVisitor.kt:33)
// 	at org.jetbrains.kotlin.backend.common.BodyLoweringVisitor.visitFunction(Lower.kt:132)
// 	at org.jetbrains.kotlin.backend.common.BodyLoweringVisitor.visitFunction(Lower.kt:132)
// 	at org.jetbrains.kotlin.ir.visitors.IrElementVisitor$DefaultImpls.visitSimpleFunction(IrElementVisitor.kt:34)
// 	at org.jetbrains.kotlin.backend.common.BodyLoweringVisitor.visitSimpleFunction(Lower.kt:132)
// 	at org.jetbrains.kotlin.backend.common.BodyLoweringVisitor.visitSimpleFunction(Lower.kt:132)
// 	at org.jetbrains.kotlin.ir.declarations.IrSimpleFunction.accept(IrSimpleFunction.kt:28)
// 	at org.jetbrains.kotlin.backend.common.LowerKt.runOnFilePostfix(Lower.kt:128)
// 	at org.jetbrains.kotlin.backend.common.LowerKt.runOnFilePostfix$default(Lower.kt:121)
// 	at org.jetbrains.kotlin.backend.common.BodyLoweringPass$DefaultImpls.lower(Lower.kt:64)
// 	at org.jetbrains.kotlin.backend.common.lower.loops.ForLoopsLowering.lower(ForLoopsLowering.kt:100)
// 	at org.jetbrains.kotlin.backend.common.LowerKt.lower(Lower.kt:67)
// 	at org.jetbrains.kotlin.ir.backend.js.JsLoweringPhasesKt$makeJsModulePhase$1.invoke(JsLoweringPhases.kt:39)
// 	at org.jetbrains.kotlin.ir.backend.js.JsLoweringPhasesKt$makeJsModulePhase$1.invoke(JsLoweringPhases.kt:38)
// 	at org.jetbrains.kotlin.ir.backend.js.JsLoweringPhasesKt$makeCustomJsModulePhase$1.invoke(JsLoweringPhases.kt:62)
// 	at org.jetbrains.kotlin.ir.backend.js.JsLoweringPhasesKt$makeCustomJsModulePhase$1.invoke(JsLoweringPhases.kt:54)
// 	at org.jetbrains.kotlin.backend.common.phaser.NamedCompilerPhase.invoke(CompilerPhase.kt:96)
// 	at org.jetbrains.kotlin.backend.common.phaser.CompositePhase.invoke(PhaseBuilders.kt:29)
// 	at org.jetbrains.kotlin.backend.common.phaser.NamedCompilerPhase.invoke(CompilerPhase.kt:96)
// 	at org.jetbrains.kotlin.backend.common.phaser.CompilerPhaseKt.invokeToplevel(CompilerPhase.kt:43)
// 	at org.jetbrains.kotlin.ir.backend.js.CompilerKt.compile(compiler.kt:136)
// 	at org.jetbrains.kotlin.ir.backend.js.CompilerKt.compile$default(compiler.kt:39)
// 	at org.jetbrains.kotlin.cli.js.K2JsIrCompiler.doExecute(K2JsIrCompiler.kt:246)
// 	at org.jetbrains.kotlin.cli.js.K2JSCompiler.doExecute(K2JSCompiler.java:182)
// 	at org.jetbrains.kotlin.cli.js.K2JSCompiler.doExecute(K2JSCompiler.java:75)
// 	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:92)
// 	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:44)
// 	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:98)
// 	at com.stepanov.bbf.bugfinder.executor.compilers.JSCompiler.executeCompiler$lambda-1(JSCompiler.kt:87)
// 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
// 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
// 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
// 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
// 	at java.base/java.lang.Thread.run(Thread.java:829)
// 